[theme]
primaryColor = "#C8102E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F3F0"
textColor = "#1D1D1D"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
